(define-class myclass (javax.media.opengl.GLEventListener)
  ((init d ::javax.media.opengl.GLAutoDrawable) ::void ())
  ((dispose d ::javax.media.opengl.GLAutoDrawable) ::void ())
  ((reshape d ::javax.media.opengl.GLAutoDrawable a ::int b ::int c ::int d ::int) ::void ())
  ((display d ::javax.media.opengl.GLAutoDrawable) ::void
  	(define gl ::javax.media.opengl.GL2 ((d:getGL):getGL2))
	(gl:glClear javax.media.opengl.GL:GL_COLOR_BUFFER_BIT)))
(define glp (javax.media.opengl.GLProfile:getDefault))
(define glcap (javax.media.opengl.GLCapabilities glp))
(define glcan ::javax.media.opengl.awt.GLCanvas (javax.media.opengl.awt.GLCanvas glcap))
(define frame ::java.awt.Frame (java.awt.Frame "Banana"))
(glcan:addGLEventListener (myclass))
(frame:setSize 500 500)
(frame:add glcan)
(frame:setVisible #t)
